name: Update GitHub Profile

on:
  schedule:
    # Runs at midnight every day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update_readme:
    name: Update README
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate dynamic stats using external APIs
      - name: Update README with Dynamic Stats
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: https://github-readme-stats.vercel.app/api?username=ShaikhEamin&show_icons=true&theme=radical

      # GitHub Activity Graph
      - name: Generate GitHub Activity Graph
        uses: ashutosh00710/github-readme-activity-graph@v0.1.6
        with:
          username: ShaikhEamin
          theme: radical

      # Commit and push changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Updated README with dynamic stats and activity graph" || echo "No changes to commit"
          git push
